# Server
server.port=8080

# Database
spring.datasource.url=jdbc:sqlserver://192.168.0.206:1433;databaseName=ONLINE_TENDERS;encrypt=false;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=barsa-2008
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=false

# JWT secret (change this to any long random string)
app.jwt.secret=SuperSuperSecretKeyThatIsAtLeast256BitsLongForJWTSigning12345678
app.jwt.expiration=86400000