# Server
server.port=8080

# Database
spring.datasource.url=jdbc:sqlserver://192.168.0.206:1433;databaseName=ONLINE_TENDERS;encrypt=false;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=barsa-2008
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=false

# JWT secret (change this to any long random string)
app.jwt.secret=SuperSuperSecretKeyThatIsAtLeast256BitsLongForJWTSigning12345678
app.jwt.expiration=86400000

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

sms.service.url=http://SMS-PROXY.energo-pro.ge/mt/oneway?username=energopro&password=EPG343&client_id=343&service_id=1

spring.mail.host=mail.energo-pro.ge
spring.mail.port=587
spring.mail.username=procurement-noreply
spring.mail.password=K$uA^]!#8q@P]4q
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=mail.energo-pro.ge

#changethis to true when going live so sms n email work
app.notifications.enabled=false