# Server
server.port=8080

# Database
spring.datasource.url=jdbc:sqlserver://${DB_HOST:192.168.0.206}:${DB_PORT:1433};databaseName=${DB_NAME:ONLINE_TENDERS};encrypt=false;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:barsa-2008}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=false

# JWT
app.jwt.secret=${JWT_SECRET:mK9!vX2$nP7@qL4&wR6!yT8*uF3^jH5+sG1-eA0=cB9/dN2~iO6|kM4.zQ7_xW3}
app.jwt.expiration=604800000
# File upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# SMS
sms.service.url=${SMS_URL:http://SMS-PROXY.energo-pro.ge/mt/oneway?username=energopro&password=EPG343&client_id=343&service_id=1}

# Email
spring.mail.host=${MAIL_HOST:mail.energo-pro.ge}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USER:procurement-noreply}
spring.mail.password=${MAIL_PASSWORD:K$uA^]!!8q@P]4q}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_HOST:mail.energo-pro.ge}

# Notifications
app.notifications.enabled=${NOTIFICATIONS_ENABLED:false}